config/routes.rb
Rails.application.routes.draw do
  resources :infomations

end

app/models/infomation.rb
class Infomation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infomations_controller.rb
class InfomationsController < ApplicationController
  before_action :set_infomation, only: [:show, :edit, :update, :destroy]

  # GET /infomations
  # GET /infomations.json
  def index
    @infomations = Infomation.all
  end

  # GET /infomations/1
  # GET /infomations/1.json
  def show
  end

  # GET /infomations/new
  def new
    @infomation = Infomation.new
  end

  # GET /infomations/1/edit
  def edit
  end

  # POST /infomations
  # POST /infomations.json
  def create
    @infomation = Infomation.new(infomation_params)

    respond_to do |format|
      if @infomation.save
        format.html { redirect_to @infomation, notice: 'Infomation was successfully created.' }
        format.json { render :show, status: :created, location: @infomation }
      else
        format.html { render :new }
        format.json { render json: @infomation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infomations/1
  # PATCH/PUT /infomations/1.json
  def update
    respond_to do |format|
      if @infomation.update(infomation_params)
        format.html { redirect_to @infomation, notice: 'Infomation was successfully updated.' }
        format.json { render :show, status: :ok, location: @infomation }
      else
        format.html { render :edit }
        format.json { render json: @infomation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infomations/1
  # DELETE /infomations/1.json
  def destroy
    @infomation.destroy
    respond_to do |format|
      format.html { redirect_to infomations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_infomation
      @infomation = Infomation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def infomation_params
      params.require(:infomation).permit(:first_name, :last_name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infomations_helper.rb
module InfomationsHelper
end

app/views/infomations/_form.html.erb
<%= form_for(@infomation) do |f| %>
  <% if @infomation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@infomation.errors.count, "error") %> prohibited this infomation from being saved:</h2>

      <ul>
      <% @infomation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infomations/edit.html.erb
<h1>Editing infomation</h1>

<%= render 'form' %>

<%= link_to 'Show', @infomation %> |
<%= link_to 'Back', infomations_path %>

app/views/infomations/index.html.erb
<h1>Listing infomations</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infomations.each do |infomation| %>
      <tr>
        <td><%= infomation.first_name %></td>
        <td><%= infomation.last_name %></td>
        <td><%= infomation.age %></td>
        <td><%= link_to 'Show', infomation %></td>
        <td><%= link_to 'Edit', edit_infomation_path(infomation) %></td>
        <td><%= link_to 'Destroy', infomation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Infomation', new_infomation_path %>
Deployed using <a href="https://www.codeship.io"></a> codeship.io</a>

app/views/infomations/new.html.erb
<h1>New infomation</h1>

<%= render 'form' %>

<%= link_to 'Back', infomations_path %>

app/views/infomations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @infomation.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @infomation.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @infomation.age %>
</p>

<%= link_to 'Edit', edit_infomation_path(@infomation) %> |
<%= link_to 'Back', infomations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Information</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>